# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\john\AppData\Local\Programs\Python\Python36-32\gikim\vip1.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1308, 505)
        font = QtGui.QFont()
        font.setFamily("Constantia")
        font.setBold(True)
        font.setWeight(75)
        Dialog.setFont(font)
        Dialog.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        Dialog.setStyleSheet("")
        self.tabWidget = QtWidgets.QTabWidget(Dialog)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 961, 491))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_4.setGeometry(QtCore.QRect(660, 20, 271, 201))
        font = QtGui.QFont()
        font.setFamily("Constantia")
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_4.setObjectName("groupBox_4")
        self.label_4 = QtWidgets.QLabel(self.groupBox_4)
        self.label_4.setGeometry(QtCore.QRect(10, 30, 101, 21))
        self.label_4.setObjectName("label_4")
        self.progressBar = QtWidgets.QProgressBar(self.groupBox_4)
        self.progressBar.setGeometry(QtCore.QRect(110, 30, 121, 21))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.label_9 = QtWidgets.QLabel(self.groupBox_4)
        self.label_9.setGeometry(QtCore.QRect(10, 70, 64, 15))
        self.label_9.setObjectName("label_9")
        self.textBrowser = QtWidgets.QTextBrowser(self.groupBox_4)
        self.textBrowser.setGeometry(QtCore.QRect(10, 90, 201, 91))
        self.textBrowser.setObjectName("textBrowser")
        self.label_4.raise_()
        self.progressBar.raise_()
        self.label_9.raise_()
        self.textBrowser.raise_()
        self.groupBox_5 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_5.setGeometry(QtCore.QRect(30, 240, 291, 181))
        font = QtGui.QFont()
        font.setFamily("Constantia")
        self.groupBox_5.setFont(font)
        self.groupBox_5.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_5.setObjectName("groupBox_5")
        self.label_17 = QtWidgets.QLabel(self.groupBox_5)
        self.label_17.setGeometry(QtCore.QRect(30, 40, 81, 21))
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.groupBox_5)
        self.label_18.setGeometry(QtCore.QRect(30, 70, 121, 21))
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.groupBox_5)
        self.label_19.setGeometry(QtCore.QRect(30, 100, 101, 16))
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.groupBox_5)
        self.label_20.setGeometry(QtCore.QRect(30, 130, 101, 21))
        self.label_20.setObjectName("label_20")
        self.textBrowser_5 = QtWidgets.QTextBrowser(self.groupBox_5)
        self.textBrowser_5.setGeometry(QtCore.QRect(110, 40, 101, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textBrowser_5.sizePolicy().hasHeightForWidth())
        self.textBrowser_5.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        self.textBrowser_5.setPalette(palette)
        self.textBrowser_5.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.textBrowser_5.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.textBrowser_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.textBrowser_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.textBrowser_5.setLineWidth(0)
        self.textBrowser_5.setMidLineWidth(-2)
        self.textBrowser_5.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textBrowser_5.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textBrowser_5.setObjectName("textBrowser_5")
        self.textBrowser_8 = QtWidgets.QTextBrowser(self.groupBox_5)
        self.textBrowser_8.setGeometry(QtCore.QRect(130, 130, 101, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textBrowser_8.sizePolicy().hasHeightForWidth())
        self.textBrowser_8.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        self.textBrowser_8.setPalette(palette)
        self.textBrowser_8.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.textBrowser_8.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.textBrowser_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.textBrowser_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.textBrowser_8.setLineWidth(0)
        self.textBrowser_8.setMidLineWidth(-2)
        self.textBrowser_8.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textBrowser_8.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textBrowser_8.setObjectName("textBrowser_8")
        self.textBrowser_6 = QtWidgets.QTextBrowser(self.groupBox_5)
        self.textBrowser_6.setGeometry(QtCore.QRect(150, 70, 101, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textBrowser_6.sizePolicy().hasHeightForWidth())
        self.textBrowser_6.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        self.textBrowser_6.setPalette(palette)
        self.textBrowser_6.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.textBrowser_6.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.textBrowser_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.textBrowser_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.textBrowser_6.setLineWidth(0)
        self.textBrowser_6.setMidLineWidth(-2)
        self.textBrowser_6.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textBrowser_6.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textBrowser_6.setObjectName("textBrowser_6")
        self.textBrowser_7 = QtWidgets.QTextBrowser(self.groupBox_5)
        self.textBrowser_7.setGeometry(QtCore.QRect(140, 100, 111, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textBrowser_7.sizePolicy().hasHeightForWidth())
        self.textBrowser_7.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        self.textBrowser_7.setPalette(palette)
        self.textBrowser_7.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.textBrowser_7.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.textBrowser_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.textBrowser_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.textBrowser_7.setLineWidth(0)
        self.textBrowser_7.setMidLineWidth(-2)
        self.textBrowser_7.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textBrowser_7.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textBrowser_7.setObjectName("textBrowser_7")
        self.groupBox_8 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_8.setGeometry(QtCore.QRect(350, 240, 291, 181))
        font = QtGui.QFont()
        font.setFamily("Constantia")
        self.groupBox_8.setFont(font)
        self.groupBox_8.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_8.setObjectName("groupBox_8")
        self.label_21 = QtWidgets.QLabel(self.groupBox_8)
        self.label_21.setGeometry(QtCore.QRect(30, 40, 81, 21))
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.groupBox_8)
        self.label_22.setGeometry(QtCore.QRect(30, 70, 121, 21))
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(self.groupBox_8)
        self.label_23.setGeometry(QtCore.QRect(30, 100, 101, 16))
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(self.groupBox_8)
        self.label_24.setGeometry(QtCore.QRect(30, 130, 101, 16))
        self.label_24.setObjectName("label_24")
        self.textBrowser_12 = QtWidgets.QTextBrowser(self.groupBox_8)
        self.textBrowser_12.setGeometry(QtCore.QRect(80, 130, 101, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textBrowser_12.sizePolicy().hasHeightForWidth())
        self.textBrowser_12.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        self.textBrowser_12.setPalette(palette)
        self.textBrowser_12.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.textBrowser_12.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.textBrowser_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.textBrowser_12.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.textBrowser_12.setLineWidth(0)
        self.textBrowser_12.setMidLineWidth(-2)
        self.textBrowser_12.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textBrowser_12.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textBrowser_12.setObjectName("textBrowser_12")
        self.textBrowser_10 = QtWidgets.QTextBrowser(self.groupBox_8)
        self.textBrowser_10.setGeometry(QtCore.QRect(130, 70, 101, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textBrowser_10.sizePolicy().hasHeightForWidth())
        self.textBrowser_10.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        self.textBrowser_10.setPalette(palette)
        self.textBrowser_10.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.textBrowser_10.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.textBrowser_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.textBrowser_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.textBrowser_10.setLineWidth(0)
        self.textBrowser_10.setMidLineWidth(-2)
        self.textBrowser_10.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textBrowser_10.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textBrowser_10.setObjectName("textBrowser_10")
        self.textBrowser_11 = QtWidgets.QTextBrowser(self.groupBox_8)
        self.textBrowser_11.setGeometry(QtCore.QRect(120, 100, 161, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textBrowser_11.sizePolicy().hasHeightForWidth())
        self.textBrowser_11.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        self.textBrowser_11.setPalette(palette)
        self.textBrowser_11.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.textBrowser_11.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.textBrowser_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.textBrowser_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.textBrowser_11.setLineWidth(0)
        self.textBrowser_11.setMidLineWidth(-2)
        self.textBrowser_11.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textBrowser_11.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textBrowser_11.setObjectName("textBrowser_11")
        self.textBrowser_9 = QtWidgets.QTextBrowser(self.groupBox_8)
        self.textBrowser_9.setGeometry(QtCore.QRect(100, 40, 101, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textBrowser_9.sizePolicy().hasHeightForWidth())
        self.textBrowser_9.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        self.textBrowser_9.setPalette(palette)
        self.textBrowser_9.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.textBrowser_9.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.textBrowser_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.textBrowser_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.textBrowser_9.setLineWidth(0)
        self.textBrowser_9.setMidLineWidth(-2)
        self.textBrowser_9.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textBrowser_9.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textBrowser_9.setObjectName("textBrowser_9")
        self.groupBox_9 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_9.setGeometry(QtCore.QRect(660, 240, 271, 181))
        font = QtGui.QFont()
        font.setFamily("Constantia")
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_9.setFont(font)
        self.groupBox_9.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_9.setObjectName("groupBox_9")
        self.textBrowser_13 = QtWidgets.QTextBrowser(self.groupBox_9)
        self.textBrowser_13.setGeometry(QtCore.QRect(10, 30, 101, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textBrowser_13.sizePolicy().hasHeightForWidth())
        self.textBrowser_13.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        self.textBrowser_13.setPalette(palette)
        self.textBrowser_13.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.textBrowser_13.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.textBrowser_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.textBrowser_13.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.textBrowser_13.setLineWidth(0)
        self.textBrowser_13.setMidLineWidth(-2)
        self.textBrowser_13.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textBrowser_13.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textBrowser_13.setObjectName("textBrowser_13")
        self.label_25 = QtWidgets.QLabel(self.groupBox_9)
        self.label_25.setGeometry(QtCore.QRect(120, 30, 81, 21))
        self.label_25.setObjectName("label_25")
        self.textBrowser_14 = QtWidgets.QTextBrowser(self.groupBox_9)
        self.textBrowser_14.setGeometry(QtCore.QRect(110, 60, 101, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textBrowser_14.sizePolicy().hasHeightForWidth())
        self.textBrowser_14.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        self.textBrowser_14.setPalette(palette)
        self.textBrowser_14.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.textBrowser_14.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.textBrowser_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.textBrowser_14.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.textBrowser_14.setLineWidth(0)
        self.textBrowser_14.setMidLineWidth(-2)
        self.textBrowser_14.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textBrowser_14.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textBrowser_14.setObjectName("textBrowser_14")
        self.label_26 = QtWidgets.QLabel(self.groupBox_9)
        self.label_26.setGeometry(QtCore.QRect(10, 60, 101, 21))
        self.label_26.setObjectName("label_26")
        self.label_27 = QtWidgets.QLabel(self.groupBox_9)
        self.label_27.setGeometry(QtCore.QRect(10, 90, 61, 21))
        self.label_27.setObjectName("label_27")
        self.textBrowser_15 = QtWidgets.QTextBrowser(self.groupBox_9)
        self.textBrowser_15.setGeometry(QtCore.QRect(70, 90, 101, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textBrowser_15.sizePolicy().hasHeightForWidth())
        self.textBrowser_15.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        self.textBrowser_15.setPalette(palette)
        self.textBrowser_15.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.textBrowser_15.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.textBrowser_15.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.textBrowser_15.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.textBrowser_15.setLineWidth(0)
        self.textBrowser_15.setMidLineWidth(-2)
        self.textBrowser_15.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textBrowser_15.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textBrowser_15.setObjectName("textBrowser_15")
        self.label_28 = QtWidgets.QLabel(self.groupBox_9)
        self.label_28.setGeometry(QtCore.QRect(10, 120, 101, 21))
        self.label_28.setObjectName("label_28")
        self.textBrowser_16 = QtWidgets.QTextBrowser(self.groupBox_9)
        self.textBrowser_16.setGeometry(QtCore.QRect(110, 120, 141, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textBrowser_16.sizePolicy().hasHeightForWidth())
        self.textBrowser_16.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        self.textBrowser_16.setPalette(palette)
        self.textBrowser_16.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.textBrowser_16.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.textBrowser_16.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.textBrowser_16.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.textBrowser_16.setLineWidth(0)
        self.textBrowser_16.setMidLineWidth(-2)
        self.textBrowser_16.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textBrowser_16.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textBrowser_16.setObjectName("textBrowser_16")
        self.groupBox_10 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_10.setGeometry(QtCore.QRect(30, 30, 601, 191))
        self.groupBox_10.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.groupBox_10.setAutoFillBackground(False)
        self.groupBox_10.setTitle("")
        self.groupBox_10.setObjectName("groupBox_10")
        self.label_11 = QtWidgets.QLabel(self.groupBox_10)
        self.label_11.setGeometry(QtCore.QRect(10, 20, 571, 161))
        self.label_11.setText("")
        self.label_11.setObjectName("label_11")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.comboBox = QtWidgets.QComboBox(self.tab_2)
        self.comboBox.setGeometry(QtCore.QRect(20, 10, 161, 31))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.stackedWidget_2 = QtWidgets.QStackedWidget(self.tab_2)
        self.stackedWidget_2.setGeometry(QtCore.QRect(10, 60, 921, 371))
        self.stackedWidget_2.setLineWidth(1)
        self.stackedWidget_2.setObjectName("stackedWidget_2")
        self.page1 = QtWidgets.QWidget()
        self.page1.setObjectName("page1")
        self.tableWidget = QtWidgets.QTableWidget(self.page1)
        self.tableWidget.setGeometry(QtCore.QRect(80, 20, 771, 341))
        self.tableWidget.setRowCount(0)
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setObjectName("tableWidget")
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(181)
        self.tableWidget.verticalHeader().setDefaultSectionSize(36)
        self.pushButton_7 = QtWidgets.QPushButton(self.page1)
        self.pushButton_7.setGeometry(QtCore.QRect(820, 410, 91, 28))
        self.pushButton_7.setObjectName("pushButton_7")
        self.stackedWidget_2.addWidget(self.page1)
        self.page2 = QtWidgets.QWidget()
        self.page2.setObjectName("page2")
        self.label_6 = QtWidgets.QLabel(self.page2)
        self.label_6.setGeometry(QtCore.QRect(270, 130, 191, 101))
        self.label_6.setObjectName("label_6")
        self.stackedWidget_2.addWidget(self.page2)
        self.page3 = QtWidgets.QWidget()
        self.page3.setObjectName("page3")
        self.label_7 = QtWidgets.QLabel(self.page3)
        self.label_7.setGeometry(QtCore.QRect(320, 130, 191, 101))
        self.label_7.setObjectName("label_7")
        self.stackedWidget_2.addWidget(self.page3)
        self.page4 = QtWidgets.QWidget()
        self.page4.setObjectName("page4")
        self.label_8 = QtWidgets.QLabel(self.page4)
        self.label_8.setGeometry(QtCore.QRect(240, 110, 191, 101))
        self.label_8.setObjectName("label_8")
        self.stackedWidget_2.addWidget(self.page4)
        self.page5 = QtWidgets.QWidget()
        self.page5.setObjectName("page5")
        self.tableWidget_2 = QtWidgets.QTableWidget(self.page5)
        self.tableWidget_2.setGeometry(QtCore.QRect(10, 230, 511, 111))
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(4)
        self.tableWidget_2.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(3, item)
        self.treeWidget = QtWidgets.QTreeWidget(self.page5)
        self.treeWidget.setGeometry(QtCore.QRect(550, 20, 351, 321))
        self.treeWidget.setAutoScrollMargin(20)
        self.treeWidget.setObjectName("treeWidget")
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        item_0.setForeground(1, brush)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        item_2.setForeground(1, brush)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        item_2.setForeground(1, brush)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        item_1.setForeground(1, brush)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        item_1.setForeground(1, brush)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        item_1.setForeground(1, brush)
        self.treeWidget.header().setDefaultSectionSize(190)
        self.treeWidget.header().setMinimumSectionSize(190)
        self.tableWidget_3 = QtWidgets.QTableWidget(self.page5)
        self.tableWidget_3.setGeometry(QtCore.QRect(10, 20, 521, 192))
        self.tableWidget_3.setObjectName("tableWidget_3")
        self.tableWidget_3.setColumnCount(4)
        self.tableWidget_3.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(3, item)
        self.stackedWidget_2.addWidget(self.page5)
        self.page6 = QtWidgets.QWidget()
        self.page6.setObjectName("page6")
        self.label_10 = QtWidgets.QLabel(self.page6)
        self.label_10.setGeometry(QtCore.QRect(240, 110, 191, 101))
        self.label_10.setObjectName("label_10")
        self.stackedWidget_2.addWidget(self.page6)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.groupBox_6 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_6.setGeometry(QtCore.QRect(10, 20, 431, 141))
        self.groupBox_6.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_6.setObjectName("groupBox_6")
        self.listWidget = QtWidgets.QListWidget(self.groupBox_6)
        self.listWidget.setGeometry(QtCore.QRect(10, 40, 401, 91))
        self.listWidget.setFlow(QtWidgets.QListView.TopToBottom)
        self.listWidget.setProperty("isWrapping", False)
        self.listWidget.setLayoutMode(QtWidgets.QListView.SinglePass)
        self.listWidget.setViewMode(QtWidgets.QListView.ListMode)
        self.listWidget.setModelColumn(0)
        self.listWidget.setObjectName("listWidget")
        item = QtWidgets.QListWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEnabled)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        self.stackedWidget = QtWidgets.QStackedWidget(self.tab_3)
        self.stackedWidget.setGeometry(QtCore.QRect(10, 180, 931, 261))
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.treeWidget_2 = QtWidgets.QTreeWidget(self.page)
        self.treeWidget_2.setGeometry(QtCore.QRect(10, 10, 571, 111))
        self.treeWidget_2.setObjectName("treeWidget_2")
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget_2)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        item_1.setForeground(0, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 140, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        item_1.setBackground(1, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 140, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        item_1.setForeground(1, brush)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        brush = QtGui.QBrush(QtGui.QColor(0, 140, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        item_1.setBackground(1, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 140, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        item_1.setForeground(1, brush)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget_2)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        brush = QtGui.QBrush(QtGui.QColor(0, 140, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        item_1.setBackground(1, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 140, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        item_1.setForeground(1, brush)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget_2)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        brush = QtGui.QBrush(QtGui.QColor(0, 140, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        item_1.setBackground(1, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 140, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        item_1.setForeground(1, brush)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        brush = QtGui.QBrush(QtGui.QColor(0, 140, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        item_1.setBackground(1, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 140, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        item_1.setForeground(1, brush)
        self.treeWidget_2.header().setDefaultSectionSize(123)
        self.tableWidget_5 = QtWidgets.QTableWidget(self.page)
        self.tableWidget_5.setGeometry(QtCore.QRect(10, 130, 901, 131))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.tableWidget_5.setFont(font)
        self.tableWidget_5.setObjectName("tableWidget_5")
        self.tableWidget_5.setColumnCount(6)
        self.tableWidget_5.setRowCount(2)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(5, item)
        self.tableWidget_5.horizontalHeader().setDefaultSectionSize(143)
        self.tableWidget_5.horizontalHeader().setStretchLastSection(True)
        self.tableWidget_5.verticalHeader().setDefaultSectionSize(44)
        self.tableWidget_5.verticalHeader().setStretchLastSection(True)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.treeWidget_3 = QtWidgets.QTreeWidget(self.page_2)
        self.treeWidget_3.setGeometry(QtCore.QRect(10, 10, 571, 111))
        self.treeWidget_3.setObjectName("treeWidget_3")
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget_3)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        brush = QtGui.QBrush(QtGui.QColor(0, 140, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        item_1.setBackground(1, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 140, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        item_1.setForeground(1, brush)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        brush = QtGui.QBrush(QtGui.QColor(0, 140, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        item_1.setBackground(1, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 140, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        item_1.setForeground(1, brush)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget_3)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        brush = QtGui.QBrush(QtGui.QColor(0, 140, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        item_1.setBackground(1, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 140, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        item_1.setForeground(1, brush)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget_3)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        brush = QtGui.QBrush(QtGui.QColor(0, 140, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        item_1.setBackground(1, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 140, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        item_1.setForeground(1, brush)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        brush = QtGui.QBrush(QtGui.QColor(0, 140, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        item_1.setBackground(1, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 140, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        item_1.setForeground(1, brush)
        self.treeWidget_3.header().setDefaultSectionSize(123)
        self.tableWidget_6 = QtWidgets.QTableWidget(self.page_2)
        self.tableWidget_6.setGeometry(QtCore.QRect(10, 130, 901, 131))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.tableWidget_6.setFont(font)
        self.tableWidget_6.setObjectName("tableWidget_6")
        self.tableWidget_6.setColumnCount(6)
        self.tableWidget_6.setRowCount(2)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_6.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_6.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_6.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_6.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_6.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_6.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_6.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_6.setHorizontalHeaderItem(5, item)
        self.tableWidget_6.horizontalHeader().setDefaultSectionSize(143)
        self.tableWidget_6.horizontalHeader().setStretchLastSection(True)
        self.tableWidget_6.verticalHeader().setDefaultSectionSize(44)
        self.tableWidget_6.verticalHeader().setStretchLastSection(True)
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.treeWidget_4 = QtWidgets.QTreeWidget(self.page_3)
        self.treeWidget_4.setGeometry(QtCore.QRect(10, 10, 571, 111))
        self.treeWidget_4.setObjectName("treeWidget_4")
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget_4)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        brush = QtGui.QBrush(QtGui.QColor(0, 140, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        item_1.setBackground(0, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        item_1.setForeground(0, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        item_1.setForeground(1, brush)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        brush = QtGui.QBrush(QtGui.QColor(0, 140, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        item_1.setBackground(0, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 140, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        item_1.setForeground(1, brush)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget_4)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        brush = QtGui.QBrush(QtGui.QColor(0, 140, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        item_1.setBackground(1, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 141, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        item_1.setForeground(1, brush)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget_4)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        brush = QtGui.QBrush(QtGui.QColor(0, 140, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        item_1.setBackground(1, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 140, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        item_1.setForeground(1, brush)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        brush = QtGui.QBrush(QtGui.QColor(0, 140, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        item_1.setBackground(1, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 140, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        item_1.setForeground(1, brush)
        self.treeWidget_4.header().setDefaultSectionSize(123)
        self.tableWidget_7 = QtWidgets.QTableWidget(self.page_3)
        self.tableWidget_7.setGeometry(QtCore.QRect(10, 130, 901, 131))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.tableWidget_7.setFont(font)
        self.tableWidget_7.setObjectName("tableWidget_7")
        self.tableWidget_7.setColumnCount(6)
        self.tableWidget_7.setRowCount(2)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_7.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_7.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_7.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_7.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_7.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_7.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_7.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_7.setHorizontalHeaderItem(5, item)
        self.tableWidget_7.horizontalHeader().setDefaultSectionSize(143)
        self.tableWidget_7.horizontalHeader().setStretchLastSection(True)
        self.tableWidget_7.verticalHeader().setDefaultSectionSize(44)
        self.tableWidget_7.verticalHeader().setStretchLastSection(True)
        self.stackedWidget.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.treeWidget_5 = QtWidgets.QTreeWidget(self.page_4)
        self.treeWidget_5.setGeometry(QtCore.QRect(10, 10, 571, 111))
        self.treeWidget_5.setObjectName("treeWidget_5")
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget_5)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        brush = QtGui.QBrush(QtGui.QColor(0, 140, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        item_1.setBackground(1, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 140, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        item_1.setForeground(1, brush)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        brush = QtGui.QBrush(QtGui.QColor(0, 140, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        item_1.setBackground(0, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 140, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        item_1.setForeground(1, brush)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget_5)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        brush = QtGui.QBrush(QtGui.QColor(0, 140, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        item_1.setBackground(1, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 140, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        item_1.setForeground(1, brush)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget_5)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        brush = QtGui.QBrush(QtGui.QColor(0, 140, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        item_1.setBackground(1, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 140, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        item_1.setForeground(1, brush)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        brush = QtGui.QBrush(QtGui.QColor(0, 140, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        item_1.setBackground(1, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 140, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        item_1.setForeground(1, brush)
        self.treeWidget_5.header().setDefaultSectionSize(123)
        self.tableWidget_8 = QtWidgets.QTableWidget(self.page_4)
        self.tableWidget_8.setGeometry(QtCore.QRect(10, 130, 901, 131))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.tableWidget_8.setFont(font)
        self.tableWidget_8.setObjectName("tableWidget_8")
        self.tableWidget_8.setColumnCount(6)
        self.tableWidget_8.setRowCount(2)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_8.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_8.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_8.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_8.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_8.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_8.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_8.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_8.setHorizontalHeaderItem(5, item)
        self.tableWidget_8.horizontalHeader().setDefaultSectionSize(143)
        self.tableWidget_8.horizontalHeader().setStretchLastSection(True)
        self.tableWidget_8.verticalHeader().setDefaultSectionSize(44)
        self.tableWidget_8.verticalHeader().setStretchLastSection(True)
        self.stackedWidget.addWidget(self.page_4)
        self.pushButton_8 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_8.setGeometry(QtCore.QRect(460, 30, 221, 31))
        font = QtGui.QFont()
        font.setFamily("Constantia")
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_8.setFont(font)
        self.pushButton_8.setStyleSheet("background-image: url(:/newPrefix/button1.JPG);")
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_9 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_9.setGeometry(QtCore.QRect(460, 70, 221, 31))
        font = QtGui.QFont()
        font.setFamily("Constantia")
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_9.setFont(font)
        self.pushButton_9.setStyleSheet("background-image: url(:/newPrefix/button1.JPG);")
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_10 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_10.setGeometry(QtCore.QRect(710, 30, 221, 31))
        font = QtGui.QFont()
        font.setFamily("Constantia")
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_10.setFont(font)
        self.pushButton_10.setStyleSheet("background-image: url(:/newPrefix/button1.JPG);")
        self.pushButton_10.setObjectName("pushButton_10")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.groupBox_11 = QtWidgets.QGroupBox(self.tab_5)
        self.groupBox_11.setGeometry(QtCore.QRect(10, 10, 581, 151))
        self.groupBox_11.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_11.setObjectName("groupBox_11")
        self.label_30 = QtWidgets.QLabel(self.groupBox_11)
        self.label_30.setGeometry(QtCore.QRect(20, 40, 101, 16))
        self.label_30.setObjectName("label_30")
        self.label_32 = QtWidgets.QLabel(self.groupBox_11)
        self.label_32.setGeometry(QtCore.QRect(20, 80, 131, 16))
        self.label_32.setObjectName("label_32")
        self.textBrowser_19 = QtWidgets.QTextBrowser(self.groupBox_11)
        self.textBrowser_19.setGeometry(QtCore.QRect(150, 72, 140, 28))
        self.textBrowser_19.setObjectName("textBrowser_19")
        self.textBrowser_20 = QtWidgets.QTextBrowser(self.groupBox_11)
        self.textBrowser_20.setGeometry(QtCore.QRect(120, 30, 140, 28))
        self.textBrowser_20.setObjectName("textBrowser_20")
        self.groupBox_12 = QtWidgets.QGroupBox(self.tab_5)
        self.groupBox_12.setGeometry(QtCore.QRect(10, 170, 581, 271))
        self.groupBox_12.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_12.setObjectName("groupBox_12")
        self.tableWidget_4 = QtWidgets.QTableWidget(self.groupBox_12)
        self.tableWidget_4.setGeometry(QtCore.QRect(10, 30, 551, 221))
        self.tableWidget_4.setObjectName("tableWidget_4")
        self.tableWidget_4.setColumnCount(4)
        self.tableWidget_4.setRowCount(5)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(3, item)
        self.tabWidget.addTab(self.tab_5, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.groupBox_7 = QtWidgets.QGroupBox(self.tab_4)
        self.groupBox_7.setGeometry(QtCore.QRect(20, 20, 571, 221))
        self.groupBox_7.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_7.setObjectName("groupBox_7")
        self.label_14 = QtWidgets.QLabel(self.groupBox_7)
        self.label_14.setGeometry(QtCore.QRect(10, 30, 61, 31))
        self.label_14.setObjectName("label_14")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.groupBox_7)
        self.textBrowser_2.setGeometry(QtCore.QRect(80, 30, 161, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        self.textBrowser_2.setPalette(palette)
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.label_15 = QtWidgets.QLabel(self.groupBox_7)
        self.label_15.setGeometry(QtCore.QRect(10, 100, 111, 16))
        self.label_15.setObjectName("label_15")
        self.textBrowser_3 = QtWidgets.QTextBrowser(self.groupBox_7)
        self.textBrowser_3.setGeometry(QtCore.QRect(112, 91, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.textBrowser_3.setFont(font)
        self.textBrowser_3.setObjectName("textBrowser_3")
        self.textBrowser_4 = QtWidgets.QTextBrowser(self.groupBox_7)
        self.textBrowser_4.setGeometry(QtCore.QRect(300, 92, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.textBrowser_4.setFont(font)
        self.textBrowser_4.setObjectName("textBrowser_4")
        self.label_16 = QtWidgets.QLabel(self.groupBox_7)
        self.label_16.setGeometry(QtCore.QRect(280, 100, 41, 16))
        self.label_16.setObjectName("label_16")
        self.label_29 = QtWidgets.QLabel(self.groupBox_7)
        self.label_29.setGeometry(QtCore.QRect(10, 160, 151, 16))
        self.label_29.setObjectName("label_29")
        self.textBrowser_17 = QtWidgets.QTextBrowser(self.groupBox_7)
        self.textBrowser_17.setGeometry(QtCore.QRect(152, 153, 161, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        self.textBrowser_17.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.textBrowser_17.setFont(font)
        self.textBrowser_17.setObjectName("textBrowser_17")
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.tabWidget.addTab(self.tab_6, "")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.tabWidget.addTab(self.tab_7, "")
        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(1010, 250, 251, 28))
        self.pushButton_2.setStyleSheet("background-image: url(:/newPrefix/button1.JPG);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(Dialog)
        self.pushButton_3.setGeometry(QtCore.QRect(1010, 290, 251, 28))
        self.pushButton_3.setStyleSheet("background-image: url(:/newPrefix/button1.JPG);")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(Dialog)
        self.pushButton_4.setGeometry(QtCore.QRect(1010, 370, 251, 28))
        self.pushButton_4.setStyleSheet("border-image: url(:/newPrefix/button1.JPG);")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(Dialog)
        self.pushButton_5.setGeometry(QtCore.QRect(1010, 330, 251, 28))
        self.pushButton_5.setStyleSheet("background-image: url(:/newPrefix/button1.JPG);")
        self.pushButton_5.setObjectName("pushButton_5")
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(1030, 60, 251, 171))
        self.groupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox.setObjectName("groupBox")
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit.setGeometry(QtCore.QRect(110, 40, 113, 21))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.lineEdit.setFont(font)
        self.lineEdit.setInputMethodHints(QtCore.Qt.ImhNone)
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(20, 40, 81, 21))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(20, 70, 64, 15))
        self.label_2.setObjectName("label_2")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_2.setGeometry(QtCore.QRect(110, 70, 113, 21))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(20, 100, 81, 16))
        self.label_3.setObjectName("label_3")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_3.setGeometry(QtCore.QRect(110, 100, 113, 21))
        self.lineEdit_3.setInputMask("")
        self.lineEdit_3.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.pushButton_6 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_6.setGeometry(QtCore.QRect(70, 130, 121, 31))
        self.pushButton_6.setStyleSheet("background-image: url(:/newPrefix/button1.JPG);")
        self.pushButton_6.setObjectName("pushButton_6")
        self.lineEdit.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.lineEdit_2.raise_()
        self.label_3.raise_()
        self.lineEdit_3.raise_()
        self.pushButton_6.raise_()
        self.groupBox_2 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_2.setGeometry(QtCore.QRect(1010, 30, 281, 211))
        self.groupBox_2.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setGeometry(QtCore.QRect(0, 30, 241, 141))
        font = QtGui.QFont()
        font.setFamily("HY견명조")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_13 = QtWidgets.QLabel(Dialog)
        self.label_13.setGeometry(QtCore.QRect(1210, 480, 91, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_13.setFont(font)
        self.label_13.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_13.setObjectName("label_13")
        self.label_12 = QtWidgets.QLabel(Dialog)
        self.label_12.setGeometry(QtCore.QRect(980, 420, 131, 71))
        self.label_12.setText("")
        self.label_12.setObjectName("label_12")

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        self.comboBox.setCurrentIndex(0)
        self.stackedWidget_2.setCurrentIndex(4)
        self.listWidget.setCurrentRow(0)
        self.stackedWidget.setCurrentIndex(0)
        self.comboBox.currentIndexChanged['int'].connect(self.stackedWidget_2.setCurrentIndex)
        self.listWidget.currentRowChanged['int'].connect(self.stackedWidget.setCurrentIndex)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "VIP v1.0.0"))
        self.groupBox_4.setTitle(_translate("Dialog", "Memoey Info"))
        self.label_4.setText(_translate("Dialog", "메모리 사용률 "))
        self.label_9.setText(_translate("Dialog", "정보"))
        self.groupBox_5.setTitle(_translate("Dialog", "User Info "))
        self.label_17.setText(_translate("Dialog", "User ID :"))
        self.label_18.setText(_translate("Dialog", "Vendor Name :"))
        self.label_19.setText(_translate("Dialog", "Location IP :"))
        self.label_20.setText(_translate("Dialog", "Last Login : "))
        self.groupBox_8.setTitle(_translate("Dialog", "S/W Info "))
        self.label_21.setText(_translate("Dialog", "Version :"))
        self.label_22.setText(_translate("Dialog", "Hypervisor :"))
        self.label_23.setText(_translate("Dialog", "Hardware :"))
        self.label_24.setText(_translate("Dialog", "Boot : "))
        self.groupBox_9.setTitle(_translate("Dialog", "CPU Info"))
        self.label_25.setText(_translate("Dialog", "Mhz"))
        self.label_26.setText(_translate("Dialog", "Archtecture :"))
        self.label_27.setText(_translate("Dialog", "Model :"))
        self.label_28.setText(_translate("Dialog", "CPU Vendor:  :"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Dialog", "Main"))
        self.comboBox.setItemText(0, _translate("Dialog", "Routing Table"))
        self.comboBox.setItemText(1, _translate("Dialog", "Static Routing"))
        self.comboBox.setItemText(2, _translate("Dialog", "RIP"))
        self.comboBox.setItemText(3, _translate("Dialog", "EIGRP"))
        self.comboBox.setItemText(4, _translate("Dialog", "OSPF"))
        self.comboBox.setItemText(5, _translate("Dialog", "BGP"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Protocol"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Subnet"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Next hop"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "Interface"))
        self.pushButton_7.setText(_translate("Dialog", "Refresh"))
        self.label_6.setText(_translate("Dialog", "미구현 "))
        self.label_7.setText(_translate("Dialog", "Rib"))
        self.label_8.setText(_translate("Dialog", "EIGRP"))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Neibor ID"))
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Dead Time"))
        item = self.tableWidget_2.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Address"))
        item = self.tableWidget_2.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "Interface"))
        self.treeWidget.headerItem().setText(0, _translate("Dialog", "Area "))
        self.treeWidget.headerItem().setText(1, _translate("Dialog", "Properties"))
        __sortingEnabled = self.treeWidget.isSortingEnabled()
        self.treeWidget.setSortingEnabled(False)
        self.treeWidget.topLevelItem(0).setText(0, _translate("Dialog", "Area ID"))
        self.treeWidget.topLevelItem(0).child(0).setText(0, _translate("Dialog", "인터페이스 수"))
        self.treeWidget.topLevelItem(0).child(0).child(0).setText(0, _translate("Dialog", "전체"))
        self.treeWidget.topLevelItem(0).child(0).child(1).setText(0, _translate("Dialog", "활성"))
        self.treeWidget.topLevelItem(0).child(1).setText(0, _translate("Dialog", "인접한 이웃 수"))
        self.treeWidget.topLevelItem(0).child(2).setText(0, _translate("Dialog", "인증 여부"))
        self.treeWidget.topLevelItem(0).child(3).setText(0, _translate("Dialog", "LSA 수"))
        self.treeWidget.setSortingEnabled(__sortingEnabled)
        item = self.tableWidget_3.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Protocol"))
        item = self.tableWidget_3.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Subnet"))
        item = self.tableWidget_3.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Next hop"))
        item = self.tableWidget_3.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "Interface"))
        self.label_10.setText(_translate("Dialog", "bgp"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Dialog", "Routing"))
        self.groupBox_6.setTitle(_translate("Dialog", "인터페이스 리스트"))
        __sortingEnabled = self.listWidget.isSortingEnabled()
        self.listWidget.setSortingEnabled(False)
        item = self.listWidget.item(0)
        item.setText(_translate("Dialog", "Ethernet eth0"))
        item = self.listWidget.item(1)
        item.setText(_translate("Dialog", "Ethernet eth1"))
        item = self.listWidget.item(2)
        item.setText(_translate("Dialog", "Ethernet eth2"))
        item = self.listWidget.item(3)
        item.setText(_translate("Dialog", "Ethernet eth3"))
        self.listWidget.setSortingEnabled(__sortingEnabled)
        self.treeWidget_2.headerItem().setText(0, _translate("Dialog", "Type"))
        self.treeWidget_2.headerItem().setText(1, _translate("Dialog", "Address"))
        __sortingEnabled = self.treeWidget_2.isSortingEnabled()
        self.treeWidget_2.setSortingEnabled(False)
        self.treeWidget_2.topLevelItem(0).setText(0, _translate("Dialog", "IPv4"))
        self.treeWidget_2.topLevelItem(0).child(0).setText(0, _translate("Dialog", "Address"))
        self.treeWidget_2.topLevelItem(0).child(1).setText(0, _translate("Dialog", "Broadcast"))
        self.treeWidget_2.topLevelItem(1).setText(0, _translate("Dialog", "IPv6"))
        self.treeWidget_2.topLevelItem(1).child(0).setText(0, _translate("Dialog", "Address"))
        self.treeWidget_2.topLevelItem(2).setText(0, _translate("Dialog", "MAC"))
        self.treeWidget_2.topLevelItem(2).child(0).setText(0, _translate("Dialog", "Address"))
        self.treeWidget_2.topLevelItem(2).child(1).setText(0, _translate("Dialog", "Broadcast"))
        self.treeWidget_2.setSortingEnabled(__sortingEnabled)
        item = self.tableWidget_5.verticalHeaderItem(0)
        item.setText(_translate("Dialog", "RX"))
        item = self.tableWidget_5.verticalHeaderItem(1)
        item.setText(_translate("Dialog", "TX"))
        item = self.tableWidget_5.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "전송량(Byte)"))
        item = self.tableWidget_5.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "패킷"))
        item = self.tableWidget_5.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "에러"))
        item = self.tableWidget_5.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "드롭"))
        item = self.tableWidget_5.horizontalHeaderItem(4)
        item.setText(_translate("Dialog", "에러율(%)"))
        item = self.tableWidget_5.horizontalHeaderItem(5)
        item.setText(_translate("Dialog", "드롭율(%)"))
        self.treeWidget_3.headerItem().setText(0, _translate("Dialog", "Type"))
        self.treeWidget_3.headerItem().setText(1, _translate("Dialog", "Address"))
        __sortingEnabled = self.treeWidget_3.isSortingEnabled()
        self.treeWidget_3.setSortingEnabled(False)
        self.treeWidget_3.topLevelItem(0).setText(0, _translate("Dialog", "IPv4"))
        self.treeWidget_3.topLevelItem(0).child(0).setText(0, _translate("Dialog", "Address"))
        self.treeWidget_3.topLevelItem(0).child(1).setText(0, _translate("Dialog", "Broadcast"))
        self.treeWidget_3.topLevelItem(1).setText(0, _translate("Dialog", "IPv6"))
        self.treeWidget_3.topLevelItem(1).child(0).setText(0, _translate("Dialog", "Address"))
        self.treeWidget_3.topLevelItem(2).setText(0, _translate("Dialog", "MAC"))
        self.treeWidget_3.topLevelItem(2).child(0).setText(0, _translate("Dialog", "Address"))
        self.treeWidget_3.topLevelItem(2).child(1).setText(0, _translate("Dialog", "Broadcast"))
        self.treeWidget_3.setSortingEnabled(__sortingEnabled)
        item = self.tableWidget_6.verticalHeaderItem(0)
        item.setText(_translate("Dialog", "RX"))
        item = self.tableWidget_6.verticalHeaderItem(1)
        item.setText(_translate("Dialog", "TX"))
        item = self.tableWidget_6.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "전송량(Byte)"))
        item = self.tableWidget_6.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "패킷"))
        item = self.tableWidget_6.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "에러"))
        item = self.tableWidget_6.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "드롭"))
        item = self.tableWidget_6.horizontalHeaderItem(4)
        item.setText(_translate("Dialog", "에러율(%)"))
        item = self.tableWidget_6.horizontalHeaderItem(5)
        item.setText(_translate("Dialog", "드롭율(%)"))
        self.treeWidget_4.headerItem().setText(0, _translate("Dialog", "Type"))
        self.treeWidget_4.headerItem().setText(1, _translate("Dialog", "Address"))
        __sortingEnabled = self.treeWidget_4.isSortingEnabled()
        self.treeWidget_4.setSortingEnabled(False)
        self.treeWidget_4.topLevelItem(0).setText(0, _translate("Dialog", "IPv4"))
        self.treeWidget_4.topLevelItem(0).child(0).setText(0, _translate("Dialog", "Address"))
        self.treeWidget_4.topLevelItem(0).child(1).setText(0, _translate("Dialog", "Broadcast"))
        self.treeWidget_4.topLevelItem(1).setText(0, _translate("Dialog", "IPv6"))
        self.treeWidget_4.topLevelItem(1).child(0).setText(0, _translate("Dialog", "Address"))
        self.treeWidget_4.topLevelItem(2).setText(0, _translate("Dialog", "MAC"))
        self.treeWidget_4.topLevelItem(2).child(0).setText(0, _translate("Dialog", "Address"))
        self.treeWidget_4.topLevelItem(2).child(1).setText(0, _translate("Dialog", "Broadcast"))
        self.treeWidget_4.setSortingEnabled(__sortingEnabled)
        item = self.tableWidget_7.verticalHeaderItem(0)
        item.setText(_translate("Dialog", "RX"))
        item = self.tableWidget_7.verticalHeaderItem(1)
        item.setText(_translate("Dialog", "TX"))
        item = self.tableWidget_7.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "전송량(Byte)"))
        item = self.tableWidget_7.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "패킷"))
        item = self.tableWidget_7.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "에러"))
        item = self.tableWidget_7.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "드롭"))
        item = self.tableWidget_7.horizontalHeaderItem(4)
        item.setText(_translate("Dialog", "에러율(%)"))
        item = self.tableWidget_7.horizontalHeaderItem(5)
        item.setText(_translate("Dialog", "드롭율(%)"))
        self.treeWidget_5.headerItem().setText(0, _translate("Dialog", "Type"))
        self.treeWidget_5.headerItem().setText(1, _translate("Dialog", "Address"))
        __sortingEnabled = self.treeWidget_5.isSortingEnabled()
        self.treeWidget_5.setSortingEnabled(False)
        self.treeWidget_5.topLevelItem(0).setText(0, _translate("Dialog", "IPv4"))
        self.treeWidget_5.topLevelItem(0).child(0).setText(0, _translate("Dialog", "Address"))
        self.treeWidget_5.topLevelItem(0).child(1).setText(0, _translate("Dialog", "Broadcast"))
        self.treeWidget_5.topLevelItem(1).setText(0, _translate("Dialog", "IPv6"))
        self.treeWidget_5.topLevelItem(1).child(0).setText(0, _translate("Dialog", "Address"))
        self.treeWidget_5.topLevelItem(2).setText(0, _translate("Dialog", "MAC"))
        self.treeWidget_5.topLevelItem(2).child(0).setText(0, _translate("Dialog", "Address"))
        self.treeWidget_5.topLevelItem(2).child(1).setText(0, _translate("Dialog", "Broadcast"))
        self.treeWidget_5.setSortingEnabled(__sortingEnabled)
        item = self.tableWidget_8.verticalHeaderItem(0)
        item.setText(_translate("Dialog", "RX"))
        item = self.tableWidget_8.verticalHeaderItem(1)
        item.setText(_translate("Dialog", "TX"))
        item = self.tableWidget_8.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "전송량(Byte)"))
        item = self.tableWidget_8.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "패킷"))
        item = self.tableWidget_8.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "에러"))
        item = self.tableWidget_8.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "드롭"))
        item = self.tableWidget_8.horizontalHeaderItem(4)
        item.setText(_translate("Dialog", "에러율(%)"))
        item = self.tableWidget_8.horizontalHeaderItem(5)
        item.setText(_translate("Dialog", "드롭율(%)"))
        self.pushButton_8.setText(_translate("Dialog", "Interface Shutdown"))
        self.pushButton_9.setText(_translate("Dialog", "Interface No Shutdown"))
        self.pushButton_10.setText(_translate("Dialog", "통계 차트"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Dialog", "Interface"))
        self.groupBox_11.setTitle(_translate("Dialog", "DHCP Rule"))
        self.label_30.setText(_translate("Dialog", "DHCP Pool :"))
        self.label_32.setText(_translate("Dialog", "DHCP Interface :"))
        self.groupBox_12.setTitle(_translate("Dialog", "DHCP Binding"))
        item = self.tableWidget_4.verticalHeaderItem(0)
        item.setText(_translate("Dialog", "1"))
        item = self.tableWidget_4.verticalHeaderItem(1)
        item.setText(_translate("Dialog", "2"))
        item = self.tableWidget_4.verticalHeaderItem(2)
        item.setText(_translate("Dialog", "3"))
        item = self.tableWidget_4.verticalHeaderItem(3)
        item.setText(_translate("Dialog", "4"))
        item = self.tableWidget_4.verticalHeaderItem(4)
        item.setText(_translate("Dialog", "5"))
        item = self.tableWidget_4.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "IP Address"))
        item = self.tableWidget_4.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "클라이언 ID"))
        item = self.tableWidget_4.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "임대기간"))
        item = self.tableWidget_4.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "종류"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("Dialog", "DHCP"))
        self.groupBox_7.setTitle(_translate("Dialog", "NAT 규칙"))
        self.label_14.setText(_translate("Dialog", "공인 IP :"))
        self.textBrowser_2.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Constantia\'; font-size:9pt; font-weight:600; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:400; font-style:italic;\">192. 168. 150. 131</span></p></body></html>"))
        self.label_15.setText(_translate("Dialog", "사설 IP 대역 :"))
        self.textBrowser_3.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Constantia\'; font-size:10pt; font-weight:600; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:400; font-style:italic;\">100.0.0.0</span></p></body></html>"))
        self.textBrowser_4.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Constantia\'; font-size:12pt; font-weight:600; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; font-weight:400; font-style:italic;\">100.0.255.255</span></p></body></html>"))
        self.label_16.setText(_translate("Dialog", "~"))
        self.label_29.setText(_translate("Dialog", "Gateway Interface :"))
        self.textBrowser_17.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Constantia\'; font-size:10pt; font-weight:600; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:400; font-style:italic;\">eth 0</span></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("Dialog", "NAT"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("Dialog", "VPN"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_7), _translate("Dialog", "ETC"))
        self.pushButton_2.setText(_translate("Dialog", "Ping"))
        self.pushButton_3.setText(_translate("Dialog", "Trace Route"))
        self.pushButton_4.setText(_translate("Dialog", "END"))
        self.pushButton_5.setText(_translate("Dialog", "About VIP"))
        self.groupBox.setTitle(_translate("Dialog", "Authentication"))
        self.label.setText(_translate("Dialog", "IP Address"))
        self.label_2.setText(_translate("Dialog", "ID"))
        self.label_3.setText(_translate("Dialog", "Password"))
        self.pushButton_6.setText(_translate("Dialog", "Login"))
        self.groupBox_2.setTitle(_translate("Dialog", "접속정보"))
        self.label_5.setText(_translate("Dialog", "TextLabel"))
        self.label_13.setText(_translate("Dialog", "VIP v1.0.1"))

import test_rc
